import IpoWidget from "./components/IpoWidget";
import HeroVideo from "./components/HeroVideo";
import { ASK_IPO_HREF, BLOG_HREF, PRIVACY_HREF, RETURNS_HREF, TERMS_HREF } from "./site-config";

const shop="https://shop.fruitypuppy.com/products/fruity-puppy";
const sample="https://shop.fruitypuppy.com/products/free-sample-fruity-puppy-original-5-shipping-amp-handling";
const base="https://shop.fruitypuppy.com/cdn/shop/files/";

const img={
  jar:base+"rn-image_picker_lib_temp_3a6190c7-8639-488e-9309-6badd5511656.png?v=1781217853&width=1200",
  hibiscus:base+"rn-image_picker_lib_temp_8152b3c5-2626-46b2-86a9-5f07fdadd850.jpg?v=1780972227&width=1200",
  aloe:base+"rn-image_picker_lib_temp_05839881-184e-42d8-bd48-5166c9bc5d68.jpg?v=1780972227&width=1200",
};

type Ingredient = {
  name:string; note:string; photo:string; botanical?:string; antioxidants?:string;
  works?:string; synergy?:string; compoundsLabel?:string;
};

const ingredients: Ingredient[]=[
  {name:"Lilikoi (Passionfruit)",note:"Fresh whole fruit",photo:"/images/ingredients/lilikoi.webp",botanical:"Passiflora edulis",antioxidants:"Piceatannol · Vitamin C · Beta-carotene",works:"Supports collagen synthesis, neutralizes free radicals, and protects skin at the cellular level.",synergy:"Enhances the absorption of other antioxidants, creating a network effect of rejuvenation."},
  {name:"Papaya",note:"Fresh whole fruit",photo:"/images/ingredients/papaya.webp",botanical:"Carica papaya",antioxidants:"Papain · Lycopene · Vitamin A",works:"Papaya enzymes dissolve dead skin and inflammation while antioxidants restore and brighten.",synergy:"Its exfoliating action preps the skin to absorb nutrients from every other ingredient."},
  {name:"Cranberry hibiscus",note:"Fresh tender tips",photo:"/images/ingredients/cranberry-hibiscus.webp",botanical:"Hibiscus acetosella",antioxidants:"Anthocyanins · Myricetin",works:"Strengthens capillaries and stimulates cellular turnover for a vibrant, even tone.",synergy:"Adds a mineral-rich foundation that boosts the effects of fruit-based antioxidants."},
  {name:"Ice cream bean",note:"Fresh tropical fruit",photo:"/images/ingredients/ice-cream-bean.webp",botanical:"Inga edulis",antioxidants:"Ferulic acid · Proanthocyanidins",works:"Provides deep cellular nourishment and defends skin DNA against oxidative damage.",synergy:"Complements the DNA-repairing qualities of papaya and lilikoi."},
  {name:"Spearmint",note:"Fresh-picked leaves",photo:"/images/ingredients/spearmint.webp",botanical:"Mentha spicata",antioxidants:"Rosmarinic acid · Luteolin",works:"Soothes inflammation, clears pores, and refreshes tired skin with a light tingle.",synergy:"Acts as a delivery agent for deeper penetration of oils and nutrients."},
  {name:"Aloe vera",note:"Fresh inner leaf",photo:"/images/ingredients/aloe-vera.webp",botanical:"Aloe barbadensis",antioxidants:"Aloin · Glucomannans · Vitamins A, C, E",works:"Rapidly penetrates skin layers to reduce inflammation, speed healing, and deliver nutrients.",synergy:"Activates the transdermal action of all the fruit extracts."},
  {name:"Shea butter",note:"Trusted butter",photo:"/images/process/butter-block.jpg",botanical:"Vitellaria paradoxa seed butter",compoundsLabel:"Lipid profile",antioxidants:"Oleic acid · Stearic acid · Linoleic acid",works:"Softens dry skin and helps reinforce the lipid layer that slows moisture loss.",synergy:"Forms part of the butter matrix that holds the fresh fruit phase against the skin."},
  {name:"Mango butter",note:"Trusted butter",photo:"/images/process/lipid-batch.jpg",botanical:"Mangifera indica seed butter",compoundsLabel:"Lipid profile",antioxidants:"Oleic acid · Stearic acid · Linoleic acid",works:"Adds rich moisture and body without making the finished cream feel excessively heavy.",synergy:"Balances the firmness of cocoa butter and the glide of coconut oil in the lipid matrix."},
  {name:"Cocoa butter",note:"Trusted butter",photo:"/images/process/cream-texture.jpg",botanical:"Theobroma cacao seed butter",compoundsLabel:"Lipid profile",antioxidants:"Stearic acid · Palmitic acid · Oleic acid",works:"Creates a firm, protective layer that helps reduce moisture loss and gives Fruity Puppy its structure.",synergy:"Its crystalline fats help organize the butters and oils around the fresh fruit particulates."},
  {name:"92° coconut oil",note:"Crystalline lipid",photo:"/images/process/open-cream.jpg",botanical:"Cocos nucifera oil",compoundsLabel:"Lipid profile",antioxidants:"Lauric acid · Myristic acid · Caprylic acid",works:"Melts on contact with skin, improves spreadability, and contributes to the cream’s protective lipid layer.",synergy:"The 92° oil helps set the texture while carrying the fresh botanical material across the skin."},
];

const sciencePanels: [string,string][]=[
  ["cells-1","Inside every fruit cell is a defense system"],["cells-2","Your skin barrier is alive"],["cells-3","Plants are intelligent"],["cells-4","We keep it alive"],
  ["lipids-1","Our crystalline matrix locks in bioactives"],["lipids-2","Fats and oils that actually care"],["lipids-3","Our crystalline matrix delivers deeper"],["lipids-4","The right fats in the right balance"],
  ["antioxidants-1","Inside a fruit’s antioxidant network"],["antioxidants-2","Papaya enzymes at work"],["antioxidants-3","Mint is more than refreshing"],["antioxidants-4","An antioxidant shield for skin"],
];

const faqs=[
  ["How do I use Fruity Puppy?","Start with a small amount on clean skin and massage it in. Use it as a daily face and body cream, or leave a thicker layer on dry, irritated, sun-exposed, tattooed, or high-stress areas."],
  ["What makes it different from natural skincare?","Most natural skincare uses a little botanical extract in a water base. Fruity Puppy is 45% whole fresh fruit, carried in a semi-crystalline matrix of trusted butters and oils."],
  ["Should I refrigerate it?","For peak performance, yes—keep Fruity Puppy refrigerated when you can. But it is made in the jungle by jungle people doing jungle things, so it is durable enough to go on adventures with you. Jessie does not have a conventional refrigerator, and his jar sits on the table beside his bed in the jungle just fine. Because Fruity Puppy is live biological skincare, think of it more like yogurt or jelly than a shelf-stable lotion: cold helps keep it at its best, but there is no reason to panic when it leaves the refrigerator. Keep the lid clean and closed, avoid direct sun or extreme heat, and put it back in the cold when you can."],
  ["Is it safe for sensitive skin?","Fruity Puppy Original was made for dry, sensitive, reactive skin. Because botanicals can affect everyone differently, check the complete ingredient list and patch test first—especially if you have allergies."],
  ["How long does one jar last?","Most customers get about four to six weeks from a 2 oz jar with regular face and body use. A little goes a long way."],
  ["What is not in it?","No essential oils, synthetic fragrance, parabens, petroleum derivatives, artificial fillers, or water as the primary ingredient. Fruity Puppy is never tested on animals."],
];

export default function Home(){return <main>
  <header id="top"><a className="logo" href="#top">FRUITY <b>PUPPY</b></a><nav><a href="/our-team">Our Team</a><a href="/our-dream">Our Dream</a><a href="/our-cream">Our Cream</a><a href="/our-home">Our Home</a><a href="/safety-and-transparency">Safety</a><a href="/lava-guava">LAVA-GUAVA</a><a href="/thorny-toad">Thorny Toad</a><a href="/moon-tea">Moon Tea</a><a href="/fpx">FPX</a><a href="/our-partners">Partners</a><a href={BLOG_HREF}>Blog</a><a className="navShop" href={shop}>Shop</a></nav><details className="mobileNav"><summary>Menu</summary><div><a href="/our-team">Our Team</a><a href="/our-dream">Our Dream</a><a href="/our-cream">Our Cream</a><a href="/our-home">Our Home</a><a href="/safety-and-transparency">Safety</a><a href="/lava-guava">LAVA-GUAVA</a><a href="/thorny-toad">Thorny Toad Face Juice</a><a href="/moon-tea">Moon Tea</a><a href="/fpx">FPX</a><a href="/our-partners">Our Partners</a><a href={BLOG_HREF}>Blog</a><a href={ASK_IPO_HREF}>Ask Ipo</a><a href={shop}>Shop</a></div></details></header>

  <section className="hero">
    <HeroVideo />
    <div className="heroCopy"><p className="tagline">REAL FRUIT SKIN CREAM FROM BIG ISLAND</p><h1>Skin eats.<br/><em>Feed it well.</em></h1><h2>45% fresh fruit and 17 antioxidants inside your skin to heal you from the inside.</h2><div className="buttonRow heroButtons"><a className="button pink heroBuy" href={shop}>Buy Now</a><a className="button heroSample" href={sample}>or get a free sample</a></div></div>
  </section>

  <section className="intro" id="why"><p className="eyebrow">More than skin cream</p><h2>This is fresh skin nutrition.</h2><p>Fruity Puppy Original is made with whole tropical fruit grown on Hawaiʻi Island—not a dusting of extract added for the label. We put the fruit on ice immediately after harvest, rupture the plant cells, and suspend those fruit particulates inside a crystalline lipid matrix your skin recognizes.</p><div className="facts"><div><b>45%</b><span>real fresh fruit</span></div><div><b>17</b><span>bioavailable antioxidants</span></div><div><b>6</b><span>Hawaiian botanicals</span></div><div><b>0</b><span>synthetic fragrance</span></div></div></section>

  <section className="productProof" aria-label="The actual Fruity Puppy product"><figure><img src="/images/process/cream-texture.jpg" alt="Close-up of the actual Fruity Puppy cream texture"/><figcaption>Actual cream texture</figcaption></figure><figure className="labeledJar"><img src={img.jar} alt="A labeled jar of Fruity Puppy Original"/><figcaption>Fruity Puppy Original</figcaption></figure></section>

  <section className="uses" id="uses"><div className="sectionHeading"><p className="eyebrow">One cream. A whole lot of jobs.</p><h2>Tell us what your skin is doing.</h2><p>Fruity Puppy supports the moisture barrier and gives stressed skin a dense network of fruit antioxidants, enzymes, and lipids—without harsh acids or synthetic fragrance.</p></div><div className="useGrid"><article><h3>Dry + sensitive skin</h3><p>Daily moisture for skin that feels tight, flaky, reactive, or over everything.</p></article><article><h3>Sun-exposed skin</h3><p>Apply it cold when skin needs cooling comfort and deep replenishment.</p></article><article><h3>Tattoos</h3><p>Rich moisture for fresh tattoo care and a stained-glass polish for older ink.</p></article><article><h3>Problem spots</h3><p>Use a thicker layer on rough patches, bites, hands, elbows, and wherever skin feels stressed.</p></article></div><a className="button pink" href={ASK_IPO_HREF}>Tell Ipo about your skin</a></section>

  <section className="ingredients" id="ingredients"><div className="sectionHeading"><p className="eyebrow">Inside Fruity Puppy Original</p><h2>Every ingredient.<br/><em>One photo at a time.</em></h2><p>The real farm and harvest photos lead. Swipe through the complete fruit-and-lipid formula. Open any ingredient to learn what it contributes to Fruity Puppy.</p></div><div className="ingredientTrack" aria-label="Fruity Puppy Original ingredients">{ingredients.map((ingredient)=><article key={ingredient.name}><img src={ingredient.photo} alt={`${ingredient.name} used in Fruity Puppy Original`}/><div><h3>{ingredient.name}</h3><p>{ingredient.note}</p>{ingredient.botanical&&<details className="ingredientDetails"><summary>What it does</summary><div className="ingredientBody"><p className="botanical">{ingredient.botanical}</p><h4>{ingredient.compoundsLabel||"Antioxidants"}</h4><p>{ingredient.antioxidants}</p><h4>How it works</h4><p>{ingredient.works}</p><h4>Synergy</h4><p>{ingredient.synergy}</p></div></details>}</div></article>)}</div></section>

  <section className="process" id="process"><div className="processCopy"><p className="eyebrow">We refused to embalm it</p><h2>Fresh-picked. Ice-extracted. Kept cold.</h2><p>Most skincare is engineered to sit on a warehouse shelf. Ours begins as food. The fruit goes on ice immediately after harvest, before oxidation gets a head start. Freezing ruptures the plant cells and releases what is inside; our butter matrix carries that fresh botanical material into the cream.</p></div><div className="processPhotos"><figure><img src="/images/process/fruit-on-ice.jpg" alt="Fresh fruit placed on ice for Fruity Puppy"/><figcaption>Fruit on ice</figcaption></figure><figure><img src="/images/process/lipid-batch.jpg" alt="Fruity Puppy botanical butter matrix being prepared"/><figcaption>Trusted butters</figcaption></figure><figure><img src="/images/actions/fresh-open-jars.webp" alt="A freshly poured batch of Fruity Puppy jars before the lids go on"/><figcaption>Fresh batch, still open</figcaption></figure></div></section>

  <section className="science" id="science"><div className="scienceIntro"><div><p className="eyebrow">Plant intelligence + human intelligence + AI</p><h2>How fruit becomes skin nutrition.</h2></div><p>Every lesson is a separate full panel—plant cells, papaya enzymes, antioxidants, and the crystalline lipid matrix. Swipe to learn.</p></div><div className="scienceTrack" aria-label="Fruity Puppy science lessons">{sciencePanels.map(([file,alt])=><figure key={file}><img src={`/images/science-panels/${file}.png`} alt={alt}/></figure>)}</div></section>

  <section className="ask askLive" id="ask-ipo"><div className="askIntro"><p className="eyebrow">Questions? Ask AI Ipo.</p><h2>Tell Ipo about your skin.</h2><p>Ipo knows the products, the botanicals, the process, and the weird things skin does. She listens first, explains the science without acting like a textbook, and helps you find the right place to start.</p></div><IpoWidget/></section>

  <section className="shopActions" id="shop-and-stay">
    <div className="shopActionIntro"><p className="eyebrow">Choose your adventure</p><h2>Feed your skin.<br/><em>Or try a little first.</em></h2><p>Go all in, start with a sample, or join the jungle mail for fresh batches, farm stories, and new drops.</p></div>
    <div className="shopActionGrid">
      <article className="actionCard buyCard"><div className="actionPhoto"><img src="/images/actions/retail-jars.webp" alt="Fruity Puppy retail jars with their pink illustrated labels"/><span>The real retail jars</span></div><div className="actionCopy"><p className="actionKicker">Ready for the real thing?</p><h3>Fruity Puppy Original</h3><p>Fresh biological skincare made with 45% whole tropical fruit.</p><a className="button pink" href={shop}>Buy Now</a></div></article>
      <article className="actionCard sampleCard"><div className="actionPhoto samplePhoto"><img src="/images/actions/sample-jar.webp" alt="A real Fruity Puppy sample jar held between two fingers"/><span>The actual sample</span></div><div className="actionCopy"><p className="actionKicker">Curious skin welcome</p><h3>Free sample</h3><p>Try Fruity Puppy Original. The sample is free—you just pay $5 for shipping.</p><a className="button dark" href={sample}>Get a Free Sample — $5 Shipping</a></div></article>
      <article className="actionCard emailCard"><div className="emailPhoto"><img src="/images/safety-blue-cabin.jpg" alt="The blue cabin in the Hawaiʻi Island jungle where Fruity Puppy is made"/><span>Jungle mail from FlashTown, Hawaiʻi</span></div><div className="emailCopy"><p className="actionKicker">Notes from the jungle</p><h3>Join our email list</h3><p>Fresh batches, farm stories, useful skin science, and whatever the jungle is doing now.</p><form action="https://shop.fruitypuppy.com/contact#contact_form" method="post" acceptCharset="UTF-8"><input type="hidden" name="form_type" value="customer"/><input type="hidden" name="utf8" value="✓"/><input type="hidden" name="contact[tags]" value="newsletter"/><label htmlFor="jungle-email">Email address</label><div className="emailField"><input id="jungle-email" type="email" name="contact[email]" autoComplete="email" placeholder="you@example.com" required/><button type="submit">Join Our Email List</button></div></form></div></article>
    </div>
  </section>

  <section className="faq" id="faq"><div className="faqIntro"><p className="eyebrow">Ipo’s Bark</p><h2>Answers before you put fruit on your face.</h2><p>Still wondering something? <a href={ASK_IPO_HREF}>Ask Ipo directly.</a></p></div><div className="faqList">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>

  <section className="cta"><img src={img.jar} alt="Fruity Puppy Original jar"/><div><p className="tagline">REAL FRUIT SKIN CREAM FROM BIG ISLAND</p><h2>Feed your skin something real.</h2><p>Fresh biological skincare, handmade in small batches on Hawaiʻi Island.</p><div className="ctaButtons"><a className="button dark" href={shop}>Buy Now</a><a className="ctaSample" href={sample}>Or try a free sample — just pay $5 shipping</a></div></div></section>

  <footer><a className="logo" href="#top">FRUITY <b>PUPPY</b></a><p>Made by hand on Big Island, Hawaiʻi.</p><div><a href="/our-team">Team</a><a href="/our-dream">Dream</a><a href="/our-cream">Cream</a><a href="/our-home">Our Home</a><a href="/safety-and-transparency">Safety</a><a href="/lava-guava">LAVA-GUAVA</a><a href="/thorny-toad">Thorny Toad</a><a href="/moon-tea">Moon Tea</a><a href="/fpx">FPX</a><a href="/our-partners">Partners</a><a href={BLOG_HREF}>Blog</a><a href={ASK_IPO_HREF}>Ask Ipo</a><a href={PRIVACY_HREF}>Privacy</a><a href={TERMS_HREF}>Terms</a><a href={RETURNS_HREF}>Returns</a></div></footer>
</main>}
