import type { Metadata } from "next";
import { ASK_IPO_HREF, BLOG_HREF, PRIVACY_HREF, RETURNS_HREF, TERMS_HREF } from "../site-config";

export const metadata: Metadata = {
  title: "Safety, Allergens & Botanical Transparency | Fruity Puppy",
  description: "Fruity Puppy ingredient, soy lecithin, botanical sensitivity, latex-fruit cross-reactivity, patch testing, storage and safe-use information.",
};

const botanicals=[
  {name:"Papaya",photo:"/images/ingredients/papaya.webp",note:"Relevant to latex–fruit cross-reactivity."},
  {name:"Lilikoi",photo:"/images/ingredients/lilikoi.webp",note:"Passionfruit; relevant to latex–fruit cross-reactivity."},
  {name:"Aloe vera",photo:"/images/ingredients/aloe-vera.webp",note:"May cause sensitivity in some individuals."},
  {name:"Spearmint",photo:"/images/ingredients/spearmint.webp",note:"Menthol-containing leaves may irritate highly sensitive skin."},
  {name:"Cranberry hibiscus",photo:"/images/ingredients/cranberry-hibiscus.webp",note:"Authentic plant material may retain trace proteins."},
  {name:"Ice cream bean",photo:"/images/ingredients/ice-cream-bean.webp",note:"A legume-family fruit used in the fresh fruit phase."},
];

function Header(){return <header id="top"><a className="logo" href="/">FRUITY <b>PUPPY</b></a><nav><a href="/our-team">Our Team</a><a href="/our-dream">Our Dream</a><a href="/our-cream">Our Cream</a><a href="/our-home">Our Home</a><a href="/safety-and-transparency">Safety</a><a href="/thorny-toad">Thorny Toad</a><a href="/our-partners">Partners</a><a href={BLOG_HREF}>Blog</a></nav><details className="mobileNav"><summary>Menu</summary><div><a href="/">Home</a><a href="/our-team">Our Team</a><a href="/our-dream">Our Dream</a><a href="/our-cream">Our Cream</a><a href="/our-home">Our Home</a><a href="/safety-and-transparency">Safety & Transparency</a><a href="/lava-guava">LAVA-GUAVA</a><a href="/thorny-toad">Thorny Toad</a><a href="/moon-tea">Moon Tea</a><a href="/fpx">FPX</a><a href="/our-partners">Partners</a><a href={BLOG_HREF}>Blog</a></div></details></header>}

export default function Page(){return <main className="safetyPage">
  <Header/>
  <section className="safetyHero"><div className="safetyHeroCopy"><p className="tagline">Real plants deserve real transparency</p><h1>Know what<br/>touches your <em>skin.</em></h1><p>Fruity Puppy and Thorny Toad are handcrafted in Hawaiʻi using authentic botanical materials. Here is what is inside, what to watch for, and how to make an informed choice.</p><div className="heroNotices"><span>External cosmetic use only</span><span>Patch test first</span><span>Refrigerate after opening</span></div></div><figure className="safetyHeroPhoto"><img src="/images/process/fruit-on-ice.jpg" alt="Fresh Fruity Puppy fruit held on ice immediately after harvest"/><figcaption>Fresh fruit · immediately on ice</figcaption></figure></section>

  <section className="soyNotice"><div><p className="eyebrow">Important ingredient disclosure</p><h2>A small amount of <em>soy-derived lecithin.</em></h2></div><div><p>Fruity Puppy uses a small amount of soy-derived lecithin as an emulsifier. It helps connect the fresh fruit phase to the butter-and-oil phase so the formula stays evenly blended.</p><p>If you have a known soy allergy or sensitivity, review the ingredient list and consult your healthcare professional before use.</p></div></section>

  <section className="botanicalPhilosophy"><div className="philosophyCopy"><p className="eyebrow">Our botanical philosophy</p><h2>Whole plants.<br/>Gentle processing.<br/>Nothing hidden.</h2><p>Our products use materials from fruits, leaves, rinds, and other plant matter. Ice extraction, fine filtration, and lipid encapsulation in a structured butter lattice aim to minimize whole-plant proteins and particulates while retaining useful botanical compounds.</p><p>Trace amounts of plant proteins or matter may remain. Processing can reduce allergenic potential; it cannot eliminate it entirely.</p></div><div className="methodCards"><article><h3>Ice extraction</h3><p>Fresh botanical material is chilled as part of the extraction process.</p></article><article><h3>Fine filtration</h3><p>Helps reduce larger pieces of plant matter in the finished preparation.</p></article><article><h3>Butter lattice</h3><p>Encapsulates the botanical phase inside Fruity Puppy’s structured lipid matrix.</p></article></div></section>

  <section className="botanicalGuide"><div className="guideHead"><p className="eyebrow">Potentially cross-reactive botanicals</p><h2>Plants are active materials.</h2><p>Our formulas may also include guava species, citrus peel, green tea, and other product-specific botanicals. These are not major allergens under U.S. federal cosmetic labeling requirements, but individual sensitivities can still occur.</p></div><div className="safetyBotanicalTrack">{botanicals.map((item)=><article key={item.name}><img src={item.photo} alt={`${item.name} used in Fruity Puppy products`}/><div><h3>{item.name}</h3><p>{item.note}</p></div></article>)}</div></section>

  <section className="latexNotice"><div className="latexImage"><img src="/images/ingredients/papaya.webp" alt="Ripe papaya used in Fruity Puppy"/><img src="/images/ingredients/lilikoi.webp" alt="Opened passionfruit used in Fruity Puppy"/></div><div><p className="eyebrow">Latex–fruit cross-reactivity</p><h2>Latex allergies can overlap with fruit sensitivities.</h2><p>Some people with latex allergy may react to botanicals with similar proteins, a phenomenon known as latex–fruit syndrome. Ingredients relevant to our formulas include papaya, passionfruit (lilikoi), and aloe vera.</p><p>If you have a diagnosed latex allergy or sensitivity, consult a healthcare professional before using these products.</p></div></section>

  <section className="reactionSection"><div><p className="eyebrow">Contact sensitivity & photosensitivity</p><h2>Listen when your skin says no.</h2><p>Citrus peel, mint, aloe, and other botanicals may increase sensitivity for some people. Possible responses include redness, itching, swelling, mild irritation, contact dermatitis, or heightened sun sensitivity—particularly with citrus-derived ingredients.</p><p>Avoid the eye area and mucous membranes. Do not apply to broken, irritated, or compromised skin. Discontinue use if irritation develops and seek medical advice when needed.</p></div><div className="patchCard"><p className="eyebrow">How to patch test</p><h3>Apply a small amount to the inner forearm.</h3><p>Leave it undisturbed for 24 hours. Watch for redness, itching, swelling, or other irritation. If a reaction occurs, do not use the product.</p></div></section>

  <section className="storageSection"><div className="storageTitle"><p className="eyebrow">Storage & handling</p><h2>Fresh skincare needs fresh habits.</h2></div><div className="storageGrid"><article><h3>Keep it cold</h3><p>Refrigerate after opening to maintain quality.</p></article><article><h3>Keep it clean</h3><p>Use clean hands or an applicator and prevent water from entering the container.</p></article><article><h3>Protect it</h3><p>Store away from direct sunlight and extreme heat.</p></article><article><h3>Expect variation</h3><p>Natural ingredients may cause small changes in color, scent, texture, or slight separation over time.</p></article></div></section>

  <section className="cabinSafety"><figure><img src="/images/safety-blue-cabin.jpg" alt="The blue production cabin in the FLASHTOWN jungle on Hawaiʻi Island"/><figcaption>The blue cabin · FLASHTOWN, Hawaiʻi</figcaption></figure><div><p className="eyebrow">Where it is made</p><h2>A cabin. In the jungle. On a volcano. At a cat sanctuary.</h2><p>That is not marketing language. It is the actual address of Fruity Puppy’s little production world: our blue cabin at FLASHTOWN, surrounded by fruit trees and more than 20 rescued cats.</p><h3>What if I’m allergic to cats?</h3><p>Cats and cat-derived materials are not ingredients and are not part of the production process. The fact that Fruity Puppy comes from a cat sanctuary should not create a cat-allergy issue for most people. If you have an unusually severe cat allergy, contact us before ordering so you can make the decision that feels safest for you.</p></div></section>

  <section className="smallBatchSafety"><div><p className="eyebrow">Small-batch production</p><h2>Made by hand in Hawaiʻi.</h2></div><div><p>Fruity Puppy and Thorny Toad are produced in small batches using traditional botanical extraction methods, in a shared facility that processes various plant materials.</p><p>These products are cosmetic preparations and have not been evaluated by the U.S. Food & Drug Administration for medical purposes. They are not intended to diagnose, treat, cure, or prevent any disease or condition. Individual responses to botanical ingredients may vary.</p><p className="updated">Last updated August 2026</p></div></section>

  <section className="safetyClosing"><p className="eyebrow">Questions about your skin?</p><h2>Ask before you apply.</h2><a className="button dark" href={ASK_IPO_HREF}>Ask Ipo</a></section>
  <footer><a className="logo" href="/">FRUITY <b>PUPPY</b></a><p>Made by hand on Big Island, Hawaiʻi.</p><div><a href="/our-home">Our Home</a><a href="/safety-and-transparency">Safety</a><a href="/our-partners">Partners</a><a href={BLOG_HREF}>Blog</a><a href={ASK_IPO_HREF}>Ask Ipo</a><a href={PRIVACY_HREF}>Privacy</a><a href={TERMS_HREF}>Terms</a><a href={RETURNS_HREF}>Returns</a></div></footer>
</main>}
