import { ASK_IPO_HREF, BLOG_HREF, PRIVACY_HREF, RETURNS_HREF, TERMS_HREF } from "../site-config";
"use client";
import {useEffect,useState} from "react";
import "./thorny.css";
const shop="https://shop.fruitypuppy.com/products/thorny-toad-face-juice",cdn="https://shop.fruitypuppy.com/cdn/shop/files/";
const bottle=cdn+"rn-image_picker_lib_temp_bc3193ff-85ca-4322-9f2a-24ed22a01afb.png?v=1781659872&width=1400";
const plants=[
 ["Stickerbush Cane","Tannins · Pore Tightening · Surface Grip","Binds to surface proteins, tightens pores, and creates the formula’s grip.",cdn+"rn-image_picker_lib_temp_9db7fb51-96db-4368-9e06-9b1df05f51a4.jpg?v=1781217619&width=1600"],
 ["Green Tea","EGCG Catechins · Antioxidant Defense","Catechins intercept free-radical damage and broaden the tannin spectrum.",cdn+"rn-image_picker_lib_temp_de50b158-6b45-4a43-814f-731099bfe21a.jpg?v=1781217138&width=1600"],
 ["Guava Leaf","Quercetin · Flavonoids · Anti-Inflammatory","Helps quiet histamine-driven reactions from a different biochemical angle.",cdn+"rn-image_picker_lib_temp_9f4a948d-589d-4b68-810d-5343670aa302.jpg?v=1781217295&width=1600"],
 ["Lemon Peel","Citric Acid · pH Alignment","Whole peel organic acids help realign skin’s surface pH after disruption.",cdn+"rn-image_picker_lib_temp_76498c68-3e34-4ff8-a4fc-73b00069d18f.jpg?v=1781217156&width=1600"],
 ["Jungle Mint","Rosmarinic Acid · Carvone · Activation","Cold-extracted whole plant—not essential oil—activates on contact.",cdn+"20251216_141734.jpg?v=1775240960&width=1600"]
];
function Header(){return <header><a className="logo" href="/">FRUITY <b>PUPPY</b></a><nav><a href="/our-team">Our Team</a><a href="/our-dream">Our Dream</a><a href="/lava-guava">LAVA-GUAVA</a><a href="/moon-tea">Moon Tea</a><a href="/fpx">FPX</a><a href={BLOG_HREF}>Blog</a><a className="navShop" href={shop}>Shop Face Juice</a></nav><details className="mobileNav"><summary>Menu</summary><div><a href="/">Home</a><a href="/our-team">Our Team</a><a href="/our-dream">Our Dream</a><a href="/lava-guava">LAVA-GUAVA</a><a href="/moon-tea">Moon Tea</a><a href={BLOG_HREF}>Blog</a><a href={shop}>Shop Face Juice</a></div></details></header>}
export default function Page(){const[a,setA]=useState(0);useEffect(()=>{const r=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("shown")),{threshold:.12});document.querySelectorAll("[data-r]").forEach(x=>r.observe(x));const p=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setA(Number((e.target as HTMLElement).dataset.p))),{rootMargin:"-35% 0px -45%"});document.querySelectorAll("[data-p]").forEach(x=>p.observe(x));return()=>{r.disconnect();p.disconnect()}},[]);return <main className="tt"><Header/>
<section className="heroT"><div data-r><p className="ey">Rare plant intelligence for the human body</p><h1>THORNY TOAD<br/><em>FACE JUICE</em></h1><p>Five volcano plants. Four functions. A fresh-brewed botanical toner that balances pH, regulates oil, reduces visible redness, and tightens pores without stripping your skin.</p><aside><a className="buttonT" href={shop}>Get Face Juice — $29.99</a><a href="#science">See how it works ↓</a></aside></div><figure><i>MUCILAGE</i><i>ACID</i><i>TANNINS</i><i>CATALYST</i><img src={bottle} alt="Thorny Toad Face Juice botanical toner"/></figure></section>
<div className="ticker"><span>NO ALCOHOL ✦ FIVE VOLCANO PLANTS ✦ NO SYNTHETIC FRAGRANCE ✦ MADE ON BIG ISLAND ✦ NO ALCOHOL ✦ FIVE VOLCANO PLANTS ✦</span></div>
<section className="introT" id="science" data-r><p className="ey">Regulation, not stripping</p><h2>Your skin has a surface chemistry.<br/>Most toners <em>disrupt it.</em></h2><p>Face Juice works with that chemistry. Mucilage holds it where you spray it. Acid aligns pH. Tannins tighten and defend. A botanical catalyst activates the system on contact.</p><div className="stats"><b>5<span>volcano plants</span></b><b>4<span>scientific tenets</span></b><b>0<span>alcohol</span></b><b>0<span>synthetic anything</span></b></div></section>
<section className="plantStory"><div className="sticky"><p className="ey">Ingredient intelligence</p><figure>{plants.map((p,i)=><img key={p[0]} className={i===a?"active":""} src={p[3]} alt={p[0]}/>)}</figure><div className="meter"><i style={{width:(a+1)*20+"%"}}/></div><small>0{a+1} / 05</small></div><div className="steps">{plants.map((p,i)=><article key={p[0]} data-p={i} data-r><span>0{i+1}</span><h2>{p[0]}</h2><h3>{p[1]}</h3><p>{p[2]}</p></article>)}</div></section>
<section className="tenets"><div data-r><p className="ey">ERV’s botanical toner framework</p><h2>The Four Tenets</h2></div><aside>{[["01","Mucilage","Hold · Hydration · Stay"],["02","Acid","pH · Balance · Restoration"],["03","Tannins","Structure · Defense · Tighten"],["04","Catalyst","Activate · Penetrate · Signal"]].map(t=><article tabIndex={0} data-r key={t[1]}><span>{t[0]}</span><h3>{t[1]}</h3><b>{t[2]}</b><i>+</i></article>)}</aside></section>
<section className="how"><div data-r><p className="ey">Thirty seconds to balance</p><h2>Cleanse.<br/>Spray.<br/><em>Let it work.</em></h2></div><ol><li data-r><b>01</b><p><strong>Start clean.</strong> Wash and pat dry.</p></li><li data-r><b>02</b><p><strong>Spray.</strong> Use 2–3 sprays directly or on a cotton pad.</p></li><li data-r><b>03</b><p><strong>Give it 30 seconds.</strong> Then moisturize if you use one.</p></li></ol></section>
<section className="finalT"><img src={bottle} alt="Thorny Toad Face Juice bottle"/><div data-r><p className="ey">2 fl oz · 59 ml · keep refrigerated</p><h2>Five plants.<br/>Four functions.<br/><em>One balanced face.</em></h2><p>No alcohol. No artificial astringents. No synthetic fragrance. Handmade on Hawaiʻi Island.</p><a className="buttonT light" href={shop}>Shop Face Juice — $29.99</a></div></section>
<footer><a className="logo" href="/">FRUITY <b>PUPPY</b></a><p>Fresh biological skincare from Big Island, Hawaiʻi.</p><div><a href="/our-team">Team</a><a href="/our-dream">Dream</a><a href={BLOG_HREF}>Blog</a><a href={ASK_IPO_HREF}>Ask Ipo</a><a href={PRIVACY_HREF}>Privacy</a><a href={TERMS_HREF}>Terms</a><a href={RETURNS_HREF}>Returns</a></div></footer></main>}
